### ISSUE TITLE
Could you unban me on discord?

### ISSUE THREAD

**Issue by akronnos** [vendetta-mod/Vendetta#107]
Hello, dear developers of this magnificent mod for discord.

I'm not exactly here to report a problem with the app, rather to appeal a ban that I believe was unfair, emotionally charged or perhaps even mistaken.

Even if I did something that upset the moderators, it's been long enough for me to have second thoughts. 

In case you decide to give me a second chance, my username on discord is the same as here.  But whatever you decide, I will respect your decision.

Sincerely,
Akron.

**Comment by ghost** [comment]
you were homophobic

**Comment by blank85** [comment]
> you were homophobic

Yeah too much homophobic and he asked for ban 
![Screenshot_20230707_174821](https://github.com/vendetta-mod/Vendetta/assets/137712947/0a8970ab-2e9b-44a4-b800-d312afbd4c06)

**Comment by nexpid** [comment]
> > you were homophobic
> 
> Yeah too much homophobic and he asked for ban ![Screenshot_20230707_174821](https://user-images.githubusercontent.com/137712947/251778347-0a8970ab-2e9b-44a4-b800-d312afbd4c06.jpg)

lmao

**Comment by akronnos** [comment]
> > you were homophobic
> 
> Yeah too much homophobic and he asked for ban ![Screenshot_20230707_174821](https://user-images.githubusercontent.com/137712947/251778347-0a8970ab-2e9b-44a4-b800-d312afbd4c06.jpg)

No, I asked to be **kicked**. The moderator just got it wrong 😩.

**Comment by nexpid** [comment]
> > > you were homophobic
> > 
> > 
> > Yeah too much homophobic and he asked for ban ![Screenshot_20230707_174821](https://user-images.githubusercontent.com/137712947/251778347-0a8970ab-2e9b-44a4-b800-d312afbd4c06.jpg)
> 
> No, I asked to be **kicked**. The moderator just got it wrong 😩.

why would you ask to be kicked in the first place

**Comment by ghost** [comment]
> > > you were homophobic
> > 
> > 
> > Yeah too much homophobic and he asked for ban ![Screenshot_20230707_174821](https://user-images.githubusercontent.com/137712947/251778347-0a8970ab-2e9b-44a4-b800-d312afbd4c06.jpg)
> 
> No, I asked to be **kicked**. The moderator just got it wrong 😩.

dawg you were homophobic there is no coming back to the server

**Comment by blank85** [comment]
> Hello, dear developers of this magnificent mod for discord.
> 
> I'm not exactly here to report a problem with the app, rather to appeal a ban that I believe was unfair, emotionally charged or perhaps even mistaken.
> 
> Even if I did something that upset the moderators, it's been long enough for me to have second thoughts.
> 
> In case you decide to give me a second chance, my username on discord is the same as here. But whatever you decide, I will respect your decision.
> 
> Sincerely, Akron.

![Screenshot_20230707_175506](https://github.com/vendetta-mod/Vendetta/assets/137712947/381f06f3-e54c-4183-ab3e-6e1ebdca904b)
You said you don't want to be a part of this community anymore. So here it is, you are no more a community member and I guess you will not be unbanned

**Comment by akronnos** [comment]
> > > > you were homophobic
> > > 
> > > 
> > > Yeah too much homophobic and he asked for ban ![Screenshot_20230707_174821](https://user-images.githubusercontent.com/137712947/251778347-0a8970ab-2e9b-44a4-b800-d312afbd4c06.jpg)
> > 
> > 
> > No, I asked to be **kicked**. The moderator just got it wrong 😩.
> 
> dawg you were homophobic there is no coming back to the server

No, please. I apologize to the entire LGBT community for my actions. And I guarantee that I changed. 😥

**Comment by akronnos** [comment]
> > Hello, dear developers of this magnificent mod for discord.
> > I'm not exactly here to report a problem with the app, rather to appeal a ban that I believe was unfair, emotionally charged or perhaps even mistaken.
> > Even if I did something that upset the moderators, it's been long enough for me to have second thoughts.
> > In case you decide to give me a second chance, my username on discord is the same as here. But whatever you decide, I will respect your decision.
> > Sincerely, Akron.
> 
> ![Screenshot_20230707_175506](https://user-images.githubusercontent.com/137712947/251780066-381f06f3-e54c-4183-ab3e-6e1ebdca904b.jpg) You said you don't want to be a part of this community anymore. So here it is, you are no more a community member and I guess you will not be unbanned

I changed my mind and genuinely want to be a part of this community now. Please think about it. ☹️

**Comment by ghost** [comment]
You have done this to yourself, before begging for things such as being kicked since "you don't want to be a part of this community anymore" you should think twice, especially since I'm pretty sure the reason you want back is to have access to plugins. I don't think you'll be unbanned anytime soon. You quite literally sent the Vendetta icon while it was pride-ified and said "look at this" "I don't want to be part of this community anymore", literally indirectly saying you're homophobic.

**Comment by akronnos** [comment]
> You have done this to yourself, before begging for things such as being kicked since "you don't want to be a part of this community anymore" you should think twice, especially since I'm pretty sure the reason you want back is to have access to plugins. I don't think you'll be unbanned anytime soon. You quite literally sent the Vendetta icon while it was pride-ified and said "look at this" "I don't want to be part of this community anymore", literally indirectly saying you're homophobic.

If it were just for the plugins, I could just create another account to access them. I just want a chance to redeem myself and apologize to people I may have offended, that's all. 🥹

**Comment by sdhhhhh** [comment]
you should krill your shelf.... NOW!

**Comment by ghost** [comment]
> If it were just for the plugins, I could just create another account to access them. I just want a chance to redeem myself and apologize to people I may have offended, that's all. 🥹

Sorry pal, not gonna happen, this ban is permanent and nothing will ever change that.

**Comment by akronnos** [comment]
> you should krill your shelf.... NOW!

Krill is a crustacean...

**Comment by akronnos** [comment]
> > If it were just for the plugins, I could just create another account to access them. I just want a chance to redeem myself and apologize to people I may have offended, that's all. 🥹
> 
> Sorry pal, not gonna happen, this ban is permanent and nothing will ever change that.

Come on, I just need a second chance to show that I've changed.

**Comment by ghost** [comment]
> Come on, I just need a second chance to show that I've changed.

One chance is enough.

**Comment by akronnos** [comment]
> > Come on, I just need a second chance to show that I've changed.
> 
> One chance is enough.

I'm begging you, please at least say you'll think about it. I accept any condition. 😞

**Comment by blank85** [comment]
> > > Come on, I just need a second chance to show that I've changed.
> > 
> > 
> > One chance is enough.
> 
> I'm begging you, please at least say you'll think about it. I accept any condition. 😞

If you keep saying continuously you want unban, the moderators will not accept your appeal

**Comment by akronnos** [comment]
> > > > Come on, I just need a second chance to show that I've changed.
> > > 
> > > 
> > > One chance is enough.
> > 
> > 
> > I'm begging you, please at least say you'll think about it. I accept any condition. 😞
> 
> If you keep saying continuously you want unban, the moderators will not accept your appeal

You are right. I should just chill and hope for the best. Thank you for your attention, you all. 🙂
