### ISSUE TITLE
does not install

### ISSUE THREAD

**Issue by Warlord0204** [vendetta-mod/Vendetta#109]
when I click on install with the vendetta manager, at the moment of injection, it displays a message saying unknown error. What should I do?

**Comment by nexpid** [comment]
press Copy Logs and pste the logs here

**Comment by Warlord0204** [comment]
Vendetta Manager v1.0.85
Built from commit 3e4ad68 on main (Changes Present)

Running Android 11, API level 30
Supported ABIs: armeabi-v7a, armeabi

Checking if base-186011.apk is cached
base-186011.apk is cached
Move base-186011.apk to working directory
Checking if config.armeabi_v7a-186011.apk is cached
config.armeabi_v7a-186011.apk is cached
Move config.armeabi_v7a-186011.apk to working directory
Checking if config.en-186011.apk is cached
config.en-186011.apk is cached
Move config.en-186011.apk to working directory
Checking if config.xxhdpi-186011.apk is cached
config.xxhdpi-186011.apk is cached
Move config.xxhdpi-186011.apk to working directory
Checking if vendetta.apk is cached
vendetta.apk is cached
Move vendetta.apk to working directory
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_square.png
Replacing mipmap-xhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxhdpi-v4 with ic_logo_foreground.png
Replacing mipmap-xxxhdpi-v4 with ic_logo_foreground.png
Reading AndroidManifest.xml from base-186011.apk
Changing package and app name in base-186011.apk
Deleting old AndroidManifest.xml in base-186011.apk
Adding patched AndroidManifest.xml in base-186011.apk
Reading AndroidManifest.xml from config.armeabi_v7a-186011.apk
Changing package and app name in config.armeabi_v7a-186011.apk
Changing package name in config.armeabi_v7a-186011.apk
Deleting old AndroidManifest.xml in config.armeabi_v7a-186011.apk
Adding patched AndroidManifest.xml in config.armeabi_v7a-186011.apk
Reading AndroidManifest.xml from config.en-186011.apk
Changing package and app name in config.en-186011.apk
Changing package name in config.en-186011.apk
Deleting old AndroidManifest.xml in config.en-186011.apk
Adding patched AndroidManifest.xm

**Comment by wingio** [comment]
The logs go beyond githubs character limit, you'll have to use a service like pastebin or gists

**Comment by Warlord0204** [comment]
https://pastebin.com/dV1R2URr

**Comment by wingio** [comment]
> https://pastebin.com/dV1R2URr

That is cut off too, try copying the logs from manager again and pasting it into pastebin

**Comment by Warlord0204** [comment]
I only found this as a log, I don't know where the rest is.

**Comment by XAlboX** [comment]
Are you using MIUI? 🤨

**Comment by Warlord0204** [comment]
yes, it's a problem?

**Comment by XAlboX** [comment]
You have to disable MIUI optimization in developer options 🥺

**Comment by Warlord0204** [comment]
oh ok thx

**Comment by Warlord0204** [comment]
it works
