### ISSUE TITLE
App shows blank with theme on Pixel

### ISSUE THREAD

**Issue by ghost** [vendetta-mod/Vendetta#119]
just the default icon theme in settings

Vendetta vs Discord

![Screenshot_20230722-183835.png](https://github.com/vendetta-mod/Vendetta/assets/94946888/fed5ce14-3142-49ee-9532-92c6865e1cfe)

**Comment by Armaldio** [comment]
How did you solved this ?

**Comment by mollyvita** [comment]
turn off themed icon in manager's settings

**Comment by Brisk-Ben** [comment]
> How did you solved this ?

I did not solve this, I only found a workaround with a shortcut app. This is a Vendetta issue because the stock Discord app has support for it but Vendetta doesn't so it shows blank.

> turn off themed icon in manager's settings 

I closed this because I figured I'd get replies like this one...
