### ISSUE TITLE
shizuku?

### ISSUE THREAD

**Issue by moongazer07** [vendetta-mod/Vendetta#120]
when will shizuku support be added?

**Comment by Cynosphere** [comment]
There's no reason for it to be added? Vendetta makes no calls that would need a root shell. The Xposed module is just for people that don't want to use patched APKs.

**Comment by rickdtc** [comment]
> when will shizuku support be added?

For what use?

**Comment by Cynosphere** [comment]
Talking with someone else that wanted this in the Discord. It's literally pointless since the people that seem to want it are just people that have a grudge against session installer for no reason other than "I don't want to tap a single button to install an app"

**Comment by rickdtc** [comment]
> Talking with someone else that wanted this in the Discord. It's literally pointless since the people that seem to want it are just people that have a grudge against session installer for no reason other than "I don't want to tap a single button to install an app"

Plus if you want to use shizuku that bad, there is lspatch

**Comment by Cynosphere** [comment]
LSPatch is already used internally by the Xposed module. The two aren't even really comparable anyways.
