### ISSUE TITLE
App doesn't launch unless webview is uninstalled

### ISSUE THREAD

**Issue by nxs-neo** [vendetta-mod/Vendetta#121]
The app wouldn't launch unless any webviews installed on the device is uninstalled. Doesn't work with Android system webview or Bromite webview installed.

**Comment by mollyvita** [comment]
rom issue

**Comment by imrobbybobby** [comment]
![Untitled30_20230725130011](https://github.com/vendetta-mod/Vendetta/assets/101864584/94b4dca7-0cc1-4c34-8c0c-be29b943cc92)
Works on my machine :TM:

**Comment by nxs-neo** [comment]
Bro wad ☠️

**Comment by Cynosphere** [comment]
React Native depends on WebView
