### ISSUE TITLE
"Show New Layout" is disabled after Vendetta restarts

### ISSUE THREAD

**Issue by GaucovyAero** [vendetta-mod/Vendetta#123]
No comment. Just gonna put a video here.

https://temp.sh/ayhBY/screen-20230727-100658.mp4

**Comment by RVZO6** [comment]
bump

**Comment by mollyvita** [comment]
just. use. experiments plugin. its simpler.

**Comment by RVZO6** [comment]
> just. use. experiments plugin. its simpler.

It's very buggy. Doesn't work all the time. Might just be me tho. It's still a bug.

**Comment by mollyvita** [comment]
> It's still a bug.

it's an experimental feature, not a bug.

**Comment by nexpid** [comment]
just don't use tabs v2

**Comment by XAlboX** [comment]
One more reason to hate Tabsv2

**Comment by XAlboX** [comment]
One more reason to hate Tabsv2

**Comment by RVZO6** [comment]
If you turn on developer options in vendetta settings, then turn on tabs ui experiment from there, and have the experiments plugin, it works ok... I think.

**Comment by mollyvita** [comment]
> If you turn on developer options 

"developer" is there for a reason, also it has nothing to do with experiments
just get plugin and turn on tabs ui experiment

**Comment by GaucovyAero** [comment]
okay thanks guys, sorry for the late response

**Comment by GaucovyAero** [comment]
uh nevermind, even doing it the other way does not save it after an app restart, works fine on stock discord :/
