### ISSUE TITLE
Theme request - ClearVision

### ISSUE THREAD

**Issue by razeNFR** [vendetta-mod/Vendetta#124]
Hello guys :)

I dont know how to make a good request, but its possible to add ClearVision to Vendetta ? 

Link to the theme : https://betterdiscord.app/theme/ClearVision

Thank you !

**Comment by nexpid** [comment]
wrong repo lmao

**Comment by nexpid** [comment]
https://github.com/vendetta-mod/ideas/issues/new/choose

**Comment by razeNFR** [comment]
Sorry i failed..
