### ISSUE TITLE
Pretty much unable to use Discord alpha

### ISSUE THREAD

**Issue by muscularcandy67** [vendetta-mod/Vendetta#137]
Since the update 193.0 Discord Alpha with Vendetta became pretty much unusable given the attached error pops up when selecting You Tab and a server folder in Tabs V2
![Screenshot_2023-08-19-10-12-33-204_dev.beefers.vendetta.jpg](https://github.com/vendetta-mod/Vendetta/assets/12277635/f9593851-70d1-420b-a41c-1875d9aa0891)
![Screenshot_2023-08-19-10-12-40-443_dev.beefers.vendetta.jpg](https://github.com/vendetta-mod/Vendetta/assets/12277635/da49bbda-c80c-41bd-8502-79e06069e694)

**Comment by muscularcandy67** [comment]
Update: the issue is now on stable branch too.
(I prefer TabsV2 so avoid telling me to disable it or to rollback to an older version, from the alpha there was plenty of time to figure out at least the underlying cause before hitting stable, but the only answers I got where to rollback/switch to stable and no one even saying "We're working on it")

**Comment by nexpid** [comment]
> no one even saying "We're working on it")

because no one figured out how to fix it? rolling back to an older version IS the only way to use Tabs V2 currently

**Comment by muscularcandy67** [comment]
Between the trials, someone tried to see if it has something to do with the new gesture (scrolling from server list to bottom bar) that reduces and center Discord's page?

**Comment by sleepingiv** [comment]
> > no one even saying "We're working on it")
> 
> because no one figured out how to fix it? rolling back to an older version IS the only way to use Tabs V2 currently

Which version is recommended for tabs v2 ?

**Comment by nexpid** [comment]
> > > no one even saying "We're working on it")
> > 
> > because no one figured out how to fix it? rolling back to an older version IS the only way to use Tabs V2 currently
> 
> Which version is recommended for tabs v2 ?

pre 193.0 ofc
