### ISSUE TITLE
Media picker is empty unless I take a photo through the app

### ISSUE THREAD

**Issue by ZirczWare** [vendetta-mod/Vendetta#140]
On normal discord it shows all of my media but on this it's empty. However, it shows pictures which I've taken through the modded app.
![Screenshot_20230827_110224](https://github.com/vendetta-mod/Vendetta/assets/57216647/7063ad22-dc5e-41b5-a8f7-9e4345e0c2c0)
![Screenshot_20230827_110249](https://github.com/vendetta-mod/Vendetta/assets/57216647/42acbbff-d5b3-4a4b-ae93-164a6bde61fd)

**Comment by AdamMReese** [comment]
I'm having the same issue

**Comment by AdamMReese** [comment]
Go to your phone settings and search "all files access." Click on it, then toggle on Vendetta.

**Comment by The-Dumb-Dino** [comment]
> Go to your phone settings and search "all files access." Click on it, then toggle on Vendetta.

New versions of Android cant just give acces unless the app asks for it.

**Comment by LordImmaculate** [comment]
> Go to your phone settings and search "all files access." Click on it, then toggle on Vendetta.

This works, you can close the issue.
