### ISSUE TITLE
I got banned for no reason…

### ISSUE THREAD

**Issue by U1TA5** [vendetta-mod/Vendetta#154]
my discord account is @.xyecoc

Hello, dear vendetta discord mods and admins. ~1 hour ago I sent to public chat a meme picture that contains p3nis haircut on someone’s head. A moderator, named @lilyfox_ gave me war and took away my permission to sent attachments. Ok. Then, like 10 minutes after it I was just talking in chat without breaking any rules, but another moderator or admin, named @lucysim just banned me with no reason. Can I get unbanned?
![IMG_0623](https://github.com/vendetta-mod/Vendetta/assets/144738232/8fb1d8f4-a087-48de-95e9-ce1f1a6c4846)
![IMG_0580](https://github.com/vendetta-mod/Vendetta/assets/144738232/d866e986-88a2-401b-84f2-a337eecdaaaf)

**Comment by jackmthws** [comment]
nuh uh

**Comment by ghost** [comment]
:husk:
