### ISSUE TITLE
discord auto return to old ui after restarting

### ISSUE THREAD

**Issue by 0123-smallbottle** [vendetta-mod/Vendetta#157]
I lost the new ui after restarting the discord
discord v197.8

sorry for my bad english
![Screenshot_2023-09-17-01-52-18-967_com.discord.png](https://github.com/vendetta-mod/Vendetta/assets/82559028/7fcd516e-f945-4530-b320-3a0b502d246d)

**Comment by XAlboX** [comment]
Enable TabsV2 in Experiments and disable Experiments plugin updates.

**Comment by 0123-smallbottle** [comment]
> Enable TabsV2 in Experiments and disable Experiments plugin updates.

that's work. thank you
