### ISSUE TITLE
Weird behaviour with Android 13 themed icons

### ISSUE THREAD

**Issue by madkarmaa** [vendetta-mod/Vendetta#167]
![Screenshot_2023-10-19-07-19-48-41_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/vendetta-mod/Vendetta/assets/100418457/7ce231f8-3406-40d6-a696-1013553a8cb8)

This is how the patched Discord app looks using the custom Vendetta icon.

App version: 193.13 stable

**Comment by Cynosphere** [comment]
Duplicate of #214 and #119
