### ISSUE TITLE
message in backticks (``) has inverse color on device theme

### ISSUE THREAD

**Issue by jirafey** [vendetta-mod/Vendetta#177]
On light mode `text` is dark and readable
On dark mode `text` is white and unreadable

Current workaround change the theme everytime you see a backtick notation.

SS light theme
![Screenshot_2023-10-30-09-20-13-511_dev beefers vendetta](https://github.com/vendetta-mod/Vendetta/assets/97115044/21dfb6e9-b038-4703-805f-e776d83f3ecd)

SS dark theme
![Screenshot_2023-10-30-09-20-26-872_dev beefers vendetta](https://github.com/vendetta-mod/Vendetta/assets/97115044/b4fa498d-4785-4263-aafc-69a861a62d02)

Phone
Xiaomi RedmI note 7

**Comment by Cynosphere** [comment]
Remove Discord from MIUI's Force Dark Mode list
