### ISSUE TITLE
[Theme Suggestion] Material Discord

### ISSUE THREAD

**Issue by razeNFR** [vendetta-mod/Vendetta#179]
_I suggest to add the theme Material Discord already existing on PC, but it will really great on mobile i think.._

**Screenshot here :**

https://user-images.githubusercontent.com/4013216/216792441-cc02a2fc-d175-432d-af75-81975d75e65e.png
https://user-images.githubusercontent.com/4013216/216792443-04fe70f0-0cd7-4d98-bb49-c937415c53d0.png
https://user-images.githubusercontent.com/4013216/216792456-36074914-4cb8-4c0b-aa07-74d09e274bcf.png
https://user-images.githubusercontent.com/4013216/216792451-676c4d76-6138-42c3-8ce2-3ee76cb82abf.png

**Link of github theme :**

https://github.com/CapnKitten/Material-Discord

**Comment by wingio** [comment]
[vendetta-mod/ideas](https://github.com/vendetta-mod/ideas)
