### ISSUE TITLE
how to use plug-ins??

### ISSUE THREAD

**Issue by MarshMeadow** [vendetta-mod/Vendetta#181]
how do i use the plug-ins/mods to do more things??

**Comment by XAlboX** [comment]
Join the Discord server and from there you can install them 🐢

**Comment by aarvndhNG** [comment]
> Join the Discord server and from there you can install them 🐢

Where I can get the discord server link

**Comment by Cynosphere** [comment]
The Discord is linked in the README. If you don't want to join you can also use https://vd-plugins.github.io/web/
