### ISSUE TITLE
Weird Arabic Script, and Application Error upon opening.

### ISSUE THREAD

**Issue by KratosAurion400** [vendetta-mod/Vendetta#187]
So first I get this error message upon opening the application which I will post screenshots of, second as mentioned above I get this weird Arabic script where the time is.

![Vendetta Error 1](https://github.com/vendetta-mod/Vendetta/assets/65616500/4e741853-0b44-41c5-b08d-973e53c29a24)
![Vendetta Error 2](https://github.com/vendetta-mod/Vendetta/assets/65616500/a824dc97-773e-4da2-86d3-72064ac97e3d)

![Arabic Script](https://github.com/vendetta-mod/Vendetta/assets/65616500/dea2f41d-434b-41ff-a388-f2bb59bc1527)

**Comment by janisslsm** [comment]
![IMG_20231112_191016.jpg](https://github.com/vendetta-mod/Vendetta/assets/97699850/677623ec-1bdf-4688-8882-e7a30d928f3e)

![IMG_20231112_122409.jpg](https://github.com/vendetta-mod/Vendetta/assets/97699850/6eaaea87-c1cd-4887-8849-efa2761f78b4)

**Comment by KratosAurion400** [comment]
> ![IMG_20231112_191016.jpg](https://user-images.githubusercontent.com/97699850/282314326-677623ec-1bdf-4688-8882-e7a30d928f3e.jpg)
> 
> ![IMG_20231112_122409.jpg](https://user-images.githubusercontent.com/97699850/282314327-6eaaea87-c1cd-4887-8849-efa2761f78b4.jpg)

Haha no worries just figured I'd inform you.
