### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JackPlaysGames0510** [vendetta-mod/Vendetta#190]
Can you please fix this for 204.0 and up please
![IMG_0051](https://github.com/vendetta-mod/Vendetta/assets/48178959/c6d1249a-29fc-46d3-a29d-8b3eacbc9974)

**Comment by jackmthws** [comment]
read

**Comment by JackPlaysGames0510** [comment]
It works fine on 203.0 and below

**Comment by JackPlaysGames0510** [comment]
And even when their is nothing their like no plugins and no theme it still appears

**Comment by JackPlaysGames0510** [comment]
https://github.com/vendetta-mod/Vendetta/assets/48178959/d56e92bb-b5db-4f09-9a67-57cbb568726d

**Comment by janisslsm** [comment]
![IMG_20231112_191016.jpg](https://github.com/vendetta-mod/Vendetta/assets/97699850/ecf039d2-adcd-49b4-a6bc-90261d2e1eb8)

![IMG_20231112_122409.jpg](https://github.com/vendetta-mod/Vendetta/assets/97699850/dd32e58d-fa16-4bb0-bf7b-4bbb20bb49d1)

**Comment by JackPlaysGames0510** [comment]
Oh right I see thanks
