### ISSUE TITLE
[Ban Appeal]

### ISSUE THREAD

**Issue by JustSxm** [vendetta-mod/Vendetta#195]
Hello,

Unfortunately not an issue but a ban appeal, as I couldnt find a link or a server to appeal on. 

I got banned for posting this cat:
![ezgif-4-6e8e986715](https://github.com/vendetta-mod/Vendetta/assets/42727829/a9bce3fd-557b-4dd9-8d4b-315ee8cb4d07)

It was literally my first day on the server getting to know people and hanging out, I was just trying to have fun with people around. When Cynthia came to say to not spam, I didnt spam (I even stopped) listening to the moderators. An hour after it happened I get banned out of the blue for "start a spam in another server". 

I was just trying to have fun and a joke turned into getting banned. Im just really confused on why I wasnt warned when it happened (and moderators were present), but banned an hour later.

I'm sorry if it pissed anyone of, I was enjoying my stay and I won't do it again if this type of gif humor is not allowed on the server

Thank you
flirtiest

**Comment by kingofcube** [comment]
ok

**Comment by maisymoe** [comment]
:troll:

**Comment by kissingboys** [comment]
This ban appeal has been denied.
You can appeal again after a minimum period of 30 days.

**Comment by SL4F** [comment]
I got banned as well for something so minor

**Comment by jsyinmn** [comment]
Mods in the server has a power abuse issue, something similar happened to me.

**Comment by imrobbybobby** [comment]
> Mods in the server has a power abuse issue, something similar happened to me.
damn man
![Screenshot 2023-11-12 183139](https://github.com/vendetta-mod/Vendetta/assets/101864584/3bd44129-d8b6-4603-80f9-e97b0e69454a)
