### ISSUE TITLE
Can i install an older version so that i dont have the new gui ?

### ISSUE THREAD

**Issue by Leclowndu93150** [vendetta-mod/Vendetta#201]

**Comment by ContinualDissapointment** [comment]
A toggle I think would be very cool, if possible.
Unsure if that would complicate or split dev work in the future.

**Comment by Poyothefluffyboyo** [comment]
You don't need it go on vendetta and install this plugin 
https://vd-plugins.github.io/proxy/maisymoe.github.io/strife/Experiments/
The new ui is an experiment thats auto turned on and can be disabled through experiments
For me i had a button when i installed it that LITERALLY said to turn it off. If you don't have that same button then go to the experiments tab and turn these things to "control" AND NOTHING ELSE 
like you see in this screenshot then restart vendetta and you're back to normal, this issue can be closed
![Screenshot_2023-12-07-11-42-38-60_ce48f3669154ad2f53ee7715a6cfbfc3](https://github.com/vendetta-mod/Vendetta/assets/153222607/01b4f023-372d-49e0-b82c-ffca3e7bc5c0)

**Comment by Leclowndu93150** [comment]
ty dude

**Comment by Poyothefluffyboyo** [comment]
I found it by complete accident so if anybody wants to fix their UI please redirect them here

**Comment by Redn2000** [comment]
I may be missing something, but after enabling these experiments and restarting I still have the new UI. Is there something else I need to turn on or edit?

**Comment by Poyothefluffyboyo** [comment]
What does yours look like? You might've set on control the wrong ones

**Comment by Redn2000** [comment]
It figures I'd find it right after commenting. I had to enable 2 others for the option to opt-out, restarted Vendetta, went into appearance and opted out of the new UI. After one more restart it worked.
![Screenshot_2023-12-07-16-34-54-29_ce48f3669154ad2f53ee7715a6cfbfc3](https://github.com/vendetta-mod/Vendetta/assets/6705326/32c151e6-d68b-442c-8346-5278eb88b47d)

**Comment by Poyothefluffyboyo** [comment]
So that means experiments are also different for everyone. So if my setup didnt work than they should follow Redn's setup for extra insurance

**Comment by Poyothefluffyboyo** [comment]
Fair warning, when you officially get the update im pretty sure some plugins might be broken, "RoleColorEverywhere" is currently broken with the error:

TypeError: Cannot convert undefined value to object
    at anonymous (Vendetta:1:5504)
    at anonymous (https://vd-plugins.github.io/proxy/fres621.github.io/vendetta-plugins/RoleColorEverywhere/:1:3813)
    at call (native)
    at rr (Vendetta:1:4945)
    at p (Vendetta:1:5717)
    at apply (Vendetta:1:5792)
    at proxy trap (native)
    at renderWithHooks (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:50929)
    at beginWork$1 (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:114470)
    at performUnitOfWork (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:100786)
    at workLoopSync (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:100668)
    at renderRootSync (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:100377)
    at performSyncWorkOnRoot (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:96719)
    at flushSyncCallbacks (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:31447)
    at batchedUpdatesImpl (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:118995)
    at batchedUpdates (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:16921)
    at _receiveRootNodeIDEvent (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:17404)
    at receiveTouches (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:268:18326)
    at apply (native)
    at __callFunction (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:4266)
    at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:825)
    at __guard (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:2908)
    at callFunctionReturnFlushedQueue (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:48:796)

**Comment by Leclowndu93150** [comment]
yeah so thats why i need to get an older version of vendetta

**Comment by Poyothefluffyboyo** [comment]
Theres not alot of plugins and the crash handler directly tells whats broken. So if you get it then a simple report post on here and turning off the plugin should be perfectly fine.

**Comment by Leclowndu93150** [comment]
okay ty

**Comment by Leclowndu93150** [comment]
it worked lol

**Comment by Poyothefluffyboyo** [comment]
Happy to help

**Comment by aschenputtel** [comment]
If you'd like to downgrade anyway — 
enable developer mode in vendetta manager (settings > about > tap version number 10 times)
scroll down to developer section, in discord version enter 205015 (or whatever version you want to downgrade to)
save all your plugins/themes/etc. then uninstall and reinstall.

**Comment by NEVARLeVrai** [comment]
Someone have an old version of vendetta?

**Comment by SodaWithoutSparkles** [comment]
i want to add that after completing the steps @Poyothefluffyboyo listed, I still could not revert to the old UI

Then I started randomly flicking experiments related to Tabs v2 to control group until I found the "show new layout" toggle, and i found out that the following combination of experiments made the toggle come back again.

![Screenshot_2023-12-21_dev.beefers.vendetta-edit.jpg](https://github.com/vendetta-mod/Vendetta/assets/64138578/c8ca8e0b-ff07-474a-ad69-d3ac4f1b0d1b)

I believe the "Tabs V2 - Panel Navigator" is the key here. 

The "Show new layout" toggle is in Settings > Appearance: New layout. You may need to long-press the :sparkles: emoji for it to re-appear.

**Comment by Leclowndu93150** [comment]
it worked for me but the switch is a laggy mess each time

**Comment by akidinatophat** [comment]
> You don't need it go on vendetta and install this plugin https://vd-plugins.github.io/proxy/maisymoe.github.io/strife/Experiments/ The new ui is an experiment thats auto turned on and can be disabled through experiments For me i had a button when i installed it that LITERALLY said to turn it off. If you don't have that same button then go to the experiments tab and turn these things to "control" AND NOTHING ELSE like you see in this screenshot then restart vendetta and you're back to normal, this issue can be closed ![Screenshot_2023-12-07-11-42-38-60_ce48f3669154ad2f53ee7715a6cfbfc3](https://private-user-images.githubusercontent.com/153222607/288848880-01b4f023-372d-49e0-b82c-ffca3e7bc5c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjI4MTcsIm5iZiI6MTcwMzg2MjUxNywicGF0aCI6Ii8xNTMyMjI2MDcvMjg4ODQ4ODgwLTAxYjRmMDIzLTM3MmQtNDllMC1iODJjLWZmY2EzZTdiYzVjMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxNTA4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTU4MTFkYjA2MjMxNjY2MzU1YzZmZTllZGI1YmE3YjA1MTk4ZjM4NDdhOTk0NTZkNDhkMjUyMDY5NGU4ZTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0LZqSBGMnYdiPxYbR6DbsW35-w6BzyPd6F698ZM3csQ)

maybe i'm missing something, but the linked page just returns a 404. is this still possible w/o downgrading or using desktop console?

**Comment by mollyvita** [comment]
> maybe i'm missing something, but the linked page just returns a 404. is this still possible w/o downgrading or using desktop console?

Vendetta - Plugins - plus icon - paste link (if not pasted automatically) - install

**Comment by akidinatophat** [comment]
o shit im dumb, tyty!
