### ISSUE TITLE
Plugins dont work

### ISSUE THREAD

**Issue by Chriswithnumber** [vendetta-mod/Vendetta#203]
![Screenshot_20231209_221903](https://github.com/vendetta-mod/Vendetta/assets/130413757/767c019a-21b2-4311-8569-5fdf573740a6)

**Comment by Meganium97** [comment]
This is a known issue affecting all channels. It's best to wait it out and see if they fix it later.

**Comment by Chriswithnumber** [comment]
> This is a known issue affecting all channels. It's best to wait it out and see if they fix it later.

Thanks 👍

**Comment by Kr0n1Ku5** [comment]
Hello? I see that this was closed. But was it ever fixed? I'm facing the same issue. I'm using the latest stable version from the manager.
