### ISSUE TITLE
builds with different package name

### ISSUE THREAD

**Issue by gmankab** [vendetta-mod/Vendetta#204]
please change package name for builds on discord.k6.tf, so then we can instal vendetta without deleting original discord

**Comment by janisslsm** [comment]
Use manager for that, unless you're talking about iOS.

**Comment by gmankab** [comment]
i am talking about android

i don't want to buid packages by myself

**Comment by Cynosphere** [comment]
That's the point of manager though is to avoid "building" anything.

**Comment by gmankab** [comment]
i think download prebuilt package is much easier than use manager

**Comment by Cynosphere** [comment]
I fail to see how downloading five APKs that require something like SAI to install and then navigating to them within SAI and selecting them, and then tapping through the customize install menu to install Vendetta is easier than pressing a button in manager and then waiting for it to download, patch and install the APKs for you.

**Comment by gmankab** [comment]
whell, install splitted apk is not as easy as install normal apk

it will be perfect to have one unsplitted apk with different package name

**Comment by janisslsm** [comment]
Use the manager, you can change the package name to whatever you want and have multiple vendetta installs if wanted + as cyno mentioned, it's 1 click install. I don't see why you're so set on the pre-patched apks.

**Comment by mollyvita** [comment]
> it will be perfect to have one unsplitted apk with different package name

uploading a modded discord apk (modding discord is forbidden by tos) on github (any company can take down the repo) in question:

**Comment by redstonekasi** [comment]
While pre-patched APKs were initially the only way of installing Vendetta on non-root devices, now the preferred method should be Manager. The only reason I haven't killed the patching service is because there seem to be people that have issues with Manager patched APKs, which is also why there will not be any more modifications to pre-patched APKs than necessary.

**Comment by gmankab** [comment]
ok, i undersood you, but i still think that publishing prebuilt apks with different package name will bee helpful for people that have issues with manager, and for people who don't want to install manager like me 

if you disagree, feel free to close issue as not planned

**Comment by meowmeowmoew3** [comment]
Sorry to intrude but jani mentioned being able to have multiple vendetta installs? How do i do that😅

**Comment by janisslsm** [comment]
> Sorry to intrude but jani mentioned being able to have multiple vendetta installs? How do i do that😅

Tap the info button in the top right and then tap the version (i think its like 10 times, i forgot) and you'll have developer settings where you can change the package name
