### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Waffle010** [vendetta-mod/Vendetta#207]
Of course, I understand that this is not the best place for an appeal, but this is the only place where I can write about it. 

And so, last night I was banned for rule 5. And I would like to ask for an unban on the server because I always do something first, then think about it, that’s the problem with me.
If you can forgive me and give me one last chance, then I will correct myself and will not make any more mistakes on the server in the future.

Nickname: _ wafffle _ (without spaces)

**Comment by IceFiles** [comment]
you forget to include the fact that you were talking about _children_ too...

**Comment by Waffle010** [comment]
> you forget to include the fact that you were talking about _children_ too...

I wasn't talking about child po. I said that some kids from Russia know about this even in 4-5 grade. I just added this to the fact. And I'm not joking, seriously

**Comment by IceFiles** [comment]
that's true but you were talking about **rule 5 stuff** and included children so it's a reasonable you would get banned for that. children may know about it (not just in Russia) but you probably shouldn't have mentioned it when talking about it

**Comment by Waffle010** [comment]
> that's true but you were talking about **rule 5 stuff** and included children so it's a reasonable you would get banned for that. children may know about it (not just in Russia) but you probably shouldn't have mentioned it when talking about it

I already realized my mistake, and realized how stupid I was then. But I’ll try to think first and then act so that this doesn’t happen again.

**Comment by ghost** [comment]
I still cannot believe you've mentioned that children know such things.

Your mistake has already left a stain on your online footprint, we do not want people talking about such things in our server, may your mistake change your actions in the present and so on. Your ban appeal is denied. Have a good night/day.
