### ISSUE TITLE
monochrome icon is blank 

### ISSUE THREAD

**Issue by leElvyn** [vendetta-mod/Vendetta#214]
There seems to be a problem with vandetta : the monochrome app icon, which is used for material you icons, is simply blank.

![Screenshot_20231222-212606](https://github.com/vendetta-mod/Vendetta/assets/45512739/876631a1-2611-405f-b7e6-058031ee5dc5)

**Comment by mollyvita** [comment]
manager - settings - change app icon (toggle off)

**Comment by gmankab** [comment]
> manager - settings - change app icon (toggle off)

please do something so you don't have to toggle it, and so that icon is not empty by default

**Comment by mollyvita** [comment]
> please do something so you don't have to toggle it, and so that icon is not empty by default

no that's your iconpack skrill issue 🦐

**Comment by gmankab** [comment]
> no that's your iconpack skrill issue 🦐

vanilla google pixel, no icon packs

**Comment by mollyvita** [comment]
themed icons still count

**Comment by Torran** [comment]
Adaptive icon support is part of the app manifest itself starting with Android 13: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

As the manager itself has adaptive icons my guess is that it's just an oversight. As this concerns the patcher itself, I suggest moving the issue to https://github.com/vendetta-mod/VendettaManager

It should be as easy as taking the icons from the original and adding them to the manifest. The relevant code that needs to be changed is at https://github.com/vendetta-mod/VendettaManager/blob/main/app/src/main/java/dev/beefers/vendetta/manager/ui/viewmodel/installer/InstallerViewModel.kt

**Comment by wingio** [comment]
manager doesn't even change any of the icon manifests, it just replaces already existing images

i don't really want to invest a lot into this since disabling the custom icon option in settings fixes the issue
