### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by the-unfunniest-lynx** [vendetta-mod/Vendetta#218]
I'm here to, unfortunately, appeal my ban.

So, chat was peacefully going on, then someone sent some text on Arabic, and then I said a dumb, racist joke, "I love people speaking terrorist", thinking absolutely nothing wrong about it for some damn reason.

I apologize to moderators and everyone who got offended, it was the fault of me and my dumb head. I'm not a racist, I swear! Could you, moderators, unban me on the server?
username: theunfunniestlynx

**Comment by wingio** [comment]
no
