### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by ItzArsen** [vendetta-mod/Vendetta#219]
Hello. My discord username is zyrxel . I was banned from Vendetta discord server without any reason, some members called me creepy.

Unban me and I am never going to use your chat again, because your server is not any friendly at all. I need themes and plugins still. Thank you.

**Comment by kingofcube** [comment]
stay mad, pedo

**Comment by danilwhale** [comment]
could you do not make shit in public server?

**Comment by ItzArsen** [comment]
Huh?

**Comment by danilwhale** [comment]
cry about it
https://tenor.com/view/dont-care-didnt-ask-cope-_ratio-skill-issue-canceled-gif-24148064

**Comment by ItzArsen** [comment]
You guys are so offensive, I didn't even offend anyone in there.

**Comment by danilwhale** [comment]
this is internet
live with this

**Comment by kingofcube** [comment]
> You guys are so offensive, I didn't even offend anyone in there.

ur a pedo

**Comment by CorruptedCas** [comment]
![ezgif com-video-to-gif-converter](https://github.com/vendetta-mod/Vendetta/assets/116581988/04f95c43-9520-4cd2-8dfa-2b71400a27f8)

**Comment by ItzArsen** [comment]
Is this how yall solve cases?

**Comment by KrstlSkll69** [comment]
yes

**Comment by dumpstercod** [comment]
womp womp

**Comment by KrstlSkll69** [comment]
> womp womp

GigaChad Moment 
![Uploading gigachad-chad.gif…]()

**Comment by KrstlSkll69** [comment]
> womp womp

GigaChad moment
https://media.tenor.com/epNMHGvRyHcAAAAC/gigachad-chad.gif

**Comment by mollyvita** [comment]
https://vd-plugins.github.io/web in question

**Comment by ItzArsen** [comment]
You got one for themes too?

**Comment by mollyvita** [comment]
no... womp womp
use anything you find on github like catppuccin
