### ISSUE TITLE
Ban appeal?

### ISSUE THREAD

**Issue by Chriswithnumber** [vendetta-mod/Vendetta#220]
I remember saying a couple of stuff to a mod and got timed out - and now banned 
Any way to get unbanned? I still need themes and plug-ins

**Comment by stikhead** [comment]
no plugins and themes for you

**Comment by sepruko** [comment]
womp womp

**Comment by Chriswithnumber** [comment]
That's wild, sad though :(

**Comment by KrstlSkll69** [comment]
> That's wild, sad though 

pluh
