### ISSUE TITLE
Where do you get the .deb files from?

### ISSUE THREAD

**Issue by TheCommandoChicken** [vendetta-mod/Vendetta#226]
Making an issue since I can't talk in the Discord without verifying by a phone number which I don't have. Where on earth do you get the .deb files from? The installation instructions for a jailbroken device say you can get them from Github actions but I don't know what that means or what I should be doing to get them. I did search in the Discord but the only files linked don't work since they require iOS 13 and I'm stuck on 12. Why can't there just be prebuilt releases like every other project?

**Comment by Cynosphere** [comment]
(written instructions are in the alt text of each image)

![1. Go to the actions tab](https://github.com/vendetta-mod/Vendetta/assets/1606710/59104274-cf03-43d1-a6de-3502a901bd4b)
![2. Click on the latest run](https://github.com/vendetta-mod/Vendetta/assets/1606710/c6023716-a3b4-4c65-97c8-de09619bf010)
![3. Select the one you need from the Artifacts section](https://github.com/vendetta-mod/Vendetta/assets/1606710/30a2a23d-5e95-414b-a0a6-167cf74b14f0)

**Comment by TheCommandoChicken** [comment]
Thank you
