### ISSUE TITLE
[Ban Appeal]

### ISSUE THREAD

**Issue by Nijjj** [vendetta-mod/Vendetta#227]
So I had been banned in vendetta discord server for like 3 months now I actually wanted to appeal for my ban today because normal discord is boring and I wanted to use vendetta but when I realised I was banned I came here because I didn't had any other way so I just wanna ask if you could unban me?
If yes then my discord id is : 750642475210637322
The reason I was banned for was nsfw messeges scattered throughout the chats.
I have changed and I would really appreciate it if you unban me.
Thank you if you did unban me :)

**Comment by aeongdesu** [comment]
shouldn't you at least leave a reason for sending?

**Comment by ghost** [comment]
If you read the rules you'll know that NSFW is not allowed under any circumstances.

**Comment by KrstlSkll69** [comment]
> If you read the rules you'll know that NSFW is not allowed under any circumstances.

pluh

**Comment by ghost** [comment]
I understand you have "changed" but as the members above said, NSFW is strictly prohibited in Vendetta, you should have read the rules when you've joined the Vendetta Discord Sever.

**Unfortunately, your ban appeal has been denied**, we cannot know for sure that "you've changed". We do not usually even accept ban appeals and most importantly, we do not need your NSFW behavior in the server.

**Comment by KrstlSkll69** [comment]
real
