### ISSUE TITLE
can apil fr

### ISSUE THREAD

**Issue by danilwhale** [vendetta-mod/Vendetta#228]
hi im roosteh
i know that i was annoying af and misused the pluralkit bot last time
first i got mute for 30 mins from fiery for misusing pluralkit and then got permaban from lucy while was taking shower :(
i promise to not be annoying anymore and forget about pk existence 🛐🛐🛐
my id is 568756569261604885 btw
![thetower](https://github.com/vendetta-mod/Vendetta/assets/61111955/cde9b5c9-6bab-4d18-a82a-25b33c4ff041)

**Comment by danilwhale** [comment]
You may want to think twice about switching out of S mode. Especially if performance and peace of mind are your top priorities. S mode was designed for security, speed, and simplicity--offering thousands of Microsoft-verified apps and Microsoft Edge, the fast and safe web browser. Please note, you will not be able to return to S mode once you've switched Get Windows 10/11 - S mode Switch with a genuine license for this PC. Get. Get.

**Comment by danilwhale** [comment]
alo

**Comment by danilwhale** [comment]
i will shitpost there until i get response :blobcatcozy:

**Comment by danilwhale** [comment]
shitpost numero 1
![RobloxPlayerBeta_jytuG7z0Jd](https://github.com/vendetta-mod/Vendetta/assets/61111955/b9783d68-951b-462b-98ce-4c62d19ec7c2)

**Comment by Not-Baguette** [comment]
I support this unban motion since rooster is one of the regulars
