### ISSUE TITLE
ban appeal again

### ISSUE THREAD

**Issue by danilwhale** [vendetta-mod/Vendetta#230]
h :superh:,
spent 3-4 days in ban and now i miss everyone i saw in chat (shed) :(
yes, i know, im annoying and weird, but i dont think it worth banning me.
i still dont understand what "bro had enough warnings" means, too many mutes, too many dumbass moments or too many warnings about pk abuse.
i apologize for my previous issue with can apil, where i said that i will shitpost. i hope you wont ban me from org for creating this issue. im ready to hear your opinion about this real ban appeal.

my id in case you will unban me this time: 568756569261604885 (@thetowerlmao)

goodbye.
i miss you all.
🛐🛐🛐

\- (annoying) rooster

**Comment by jackmthws** [comment]
![image](https://github.com/vendetta-mod/Vendetta/assets/30497388/89294904-7a5a-4da5-8072-7a4e11b2232b)

**Comment by nexpid** [comment]
Jesus Christ can you just DM staff once instead of making a bajilion GitHub issues

**Comment by danilwhale** [comment]
oh, sorry, i didnt knew that i can dm staff lol. i thought ban appeals are made only in issues.

**Comment by KrstlSkll69** [comment]
> oh, sorry, i didnt knew that i can dm staff lol. i thought ban appeals are made only in issues.

pluh

**Comment by danilwhale** [comment]
> > oh, sorry, i didnt knew that i can dm staff lol. i thought ban appeals are made only in issues.
> 
> pluh

womp womp

**Comment by KrstlSkll69** [comment]
> > > oh, sorry, i didnt knew that i can dm staff lol. i thought ban appeals are made only in issues.
> > 
> > 
> > pluh
> 
> womp womp

indeed

**Comment by danilwhale** [comment]
okay, waiting for response.

**Comment by nexpid** [comment]
mate you're not getting unbanned

**Comment by danilwhale** [comment]
cool

**Comment by danilwhale** [comment]
i will miss you all 🫡

**Comment by ghost** [comment]
> oh, sorry, i didnt knew that i can dm staff lol. i thought ban appeals are made only in issues.

We never ever stated we allow ban appeals in issues, actually, **most bans are not even appealable**. I would like to say that you are, un**fortunately** not getting unbanned. You were muted for PluralKit abuse and another mute which was supposed to last 5 years from Lucysim, unfortunately for the latter one I don't have a specific reason.

**Comment by danilwhale** [comment]
gn eep well then.
