### ISSUE TITLE
Injecting vendetta fail

### ISSUE THREAD

**Issue by Cerolessly** [vendetta-mod/Vendetta#51]
When ever I try to inject vendetta it fails I've tried clearing cache and reinstalling the app 
![Screenshot_20230407-224306_Vendetta Manager](https://user-images.githubusercontent.com/130226687/230721544-2a0ad689-5bf8-4773-b03f-22ab473f77f8.jpg)

**Comment by maisymoe** [comment]
Can you copy the logs and upload them somewhere, please?

**Comment by Cerolessly** [comment]
https://hastebin.com/share/kexadometu.bash
