### ISSUE TITLE
Vendetta not installing

### ISSUE THREAD

**Issue by ghost** [vendetta-mod/Vendetta#53]
I can't install Vendetta from the manager (see screenshot). Also the prebuilt APKs either don't open or crash on startup when I can install them

![Screenshot_2023-04-09-12-55-46-204_dev beefers vendetta manager](https://user-images.githubusercontent.com/83910019/230768536-1e02936f-45e7-4043-8407-b3fc939b026e.jpg)

**Comment by Glorp3179** [comment]
Based on your phone's UI, you're using a Xiaomi device. Turning off your MIUI optimization before installing will solve the problem, then you can turn it back on after the installation. If you don't know how to find the setting there's plenty of tutorials online
