### ISSUE TITLE
Incomplete language libary

### ISSUE THREAD

**Issue by a-usr** [vendetta-mod/Vendetta#58]
Only English available. Slightly annoying.

**Comment by maisymoe** [comment]
Do you mean Discord's UI not correctly using the chosen language? If so, that's a known bug with Manager builds of Vendetta that is being looked into.

If you mean that Vendetta's UI does not respond to Discord's language, we have not implemented internationalisation at all. It is something I wanted to do later down the line, though.

**Comment by a-usr** [comment]
Well yes, but not exactly what you described. Even though discord was set to german by default (guess why), the UI was still displayed in english. This suggests that the other languages aren't existent or loaded, no?

**Comment by maisymoe** [comment]
> This suggests that the other languages aren't existent or loaded, no?

As I mentioned before, currently any version of Vendetta installed from the Manager app causes Discord to not respect your chosen language. This, of course, would mean that even if Discord chose German by default, it would not work as intended. This is a bug, and we're looking into it.

**Comment by maisymoe** [comment]
Even if this bug was not present, Vendetta's UI (e.g. the settings) is hard-coded to be in English. We have no translations set up as of right now. It is something I want to do, though. 

I hope the two above comments clarify things :)

**Comment by a-usr** [comment]
> Even if this bug was not present, Vendetta's UI (e.g. the settings) is hard-coded to be in English. We have no translations set up as of right now. It is something I want to do, though. 
I can help you with that for the German part

**Comment by a-usr** [comment]
> Even if this bug was not present, Vendetta's UI (e.g. the settings) is hard-coded to be in English. We have no translations set up as of right now. It is something I want to do, though.

I can help you with translating it to German
