### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by fangykai** [vendetta-mod/Vendetta#66]
Basically after installing the base360-apk (172023, 172024 and 176208)

They just don't open. No errors, just crash.

However, Aliucord can install just fine.

Info:

Nubia RedMagic 5g
No Root
Android 11

**Comment by maisymoe** [comment]
Use [VendettaManager](https://github.com/vendetta-mod/VendettaManager)

**Comment by fangykai** [comment]
I can't. Which is why I went for the APK.

Scratch my stupid comment - saw it has an APK as well.

**Comment by fangykai** [comment]
Thanks for this :D however no icons show at the bottom bar except for my profile icon.

**Comment by BNKdesigns** [comment]
Same problem but the manager wont download (iran internet problems) so I installed the prebuilt and it just crashes at startup
