### ISSUE TITLE
Vendetta Manager says Loading... Instead of Install.

### ISSUE THREAD

**Issue by Sparkkkkie** [vendetta-mod/Vendetta#69]
Trying to install vendetta, normal apk just crashed on startup tried all 8 of the apks and also stable beta and alpha nothing worked, now I'm trying the manager route but it's stuck on loading.. no install nothing
See the pic
My phone is Samsung a54 5G.
![Screenshot_20230425_011742_Vendetta Manager](https://user-images.githubusercontent.com/98154338/234135861-2b7def07-ee84-458c-9159-1abcc0d0d02c.jpg)

**Comment by maisymoe** [comment]
The APKs not starting is usually because they have not been installed correctly (using Split APK Installer), but the manager "Loading" issue comes from your network refusing to load _something_ to do with Vendetta's update process. It may work on mobile data, or a different network.

**Comment by wingio** [comment]
it could be the vpn

**Comment by Sparkkkkie** [comment]
> 

Yup thanks, I always use an adblock and vpn for my security guess it blocked it.

**Comment by KindaNeatdoe** [comment]
Same issue, but I have no VPN/adblock/whatever. Could it be some isp / DNS block? I'd use mobile data(it works) but I'm on a limited plan. Any help?

**Comment by XAlboX** [comment]
Use Google DNS or any other DNS provider to unblock it
