### ISSUE TITLE
Themes do not respect text zoom level

### ISSUE THREAD

**Issue by esibun** [vendetta-mod/Vendetta#73]
Background:
Under appearance, Discord users are able to change the text zoom size down to 75%.  This affects most text in the application including the channel list, chat window and member list.  These are all part of what is themed by the theme engine.

Steps to Reproduce:
1. Go to settings -> appearance
2. Set text zoom level to 75%
3. Go back to main application window
4. Allow Discord to get backgrounded by Android (i.e. by switching around applications in Android)
5. Switch back to Discord

Expected Behavior:
All text items in Discord remain at 75%

Actual Behavior:
- Chat window remains at 75% (as expected)
- Channel list, member list and options text are forced to 100%.  Sometimes I have noticed this happens inconsistently; some items will be at 75% and others in the same window will be at 100%

This seems to happen only when a theme is enabled - I also tried disabling all themes and was no longer able to reproduce the issue, so it would appear the problem lies somewhere in the theming engine.

Screenshot for demonstration purposes:
![Screenshot_20230428-100235](https://user-images.githubusercontent.com/2644839/235172747-ce8e5516-cca6-482b-b6bd-ec2f728c3cd9.png)

**Comment by maisymoe** [comment]
I'm unable to reproduce this even with a theme turned on... Which Discord version is this?

**Comment by esibun** [comment]
Sorry, this should have been included in the original bug report:

App: 175.16 (175016) googleRelease;
Manifest: "84fc41c23bbdd32340702165ad519926";
Build Override: N/A;
Device: raven (Pixel 6 Pro) OS 33;

Vendetta - f66e62d;
Discord - 175.16 (175016);
React - 18.2.0;
React Native - 0.70.6;
Bytecode - 89;

Loader - VendettaXposed;
Operating System - Android 13;
SDK - 33;
Manufacturer - Google;
Brand - google;
Model - Pixel 6 Pro;
Codename - raven;

Running GrapheneOS 2023041100.  I reproduced with two separate themes; Monokai Night and Orion.  It's possible its a theme issue but I think it's unlikely given it occured with multiple themes.

I would expect reproduction to be finicky given the deallocation requirement.  Also very much a possibility that it could be related to GrapheneOS.

I'll try playing with the developer tools this weekend to see if I can find anything further that would help with reproduction.

**Comment by maisymoe** [comment]
It could also be an issue with Discord itself, considering I cannot reproduce this on 177.7.

**Comment by esibun** [comment]
And seemingly as always when I report these issues I can't seem to get it to happen anymore.  I'll chalk it up to either a Discord update or a plugin issue for now.

Will reopen if I find anything new.

**Comment by esibun** [comment]
Just in case anyone finds this issue in future this does seem to be a Discord issue and not a mod issue.  This reproduced on 177.9 with some difficulty without any plugins and on 175.16 without any themes.  That would seem to point the finger at Discord since although I didn't check native client because reproducing this is actually pretty annoying, there's nothing common to the mod.

Adjusting the font size in the OS seems to be more stable for me although obviously other programs will also be affected.
