### ISSUE TITLE
[Feature Request] Support for Material You theming.

### ISSUE THREAD

**Issue by soymadip** [vendetta-mod/Vendetta#74]
Although vendetta has custom theme support but it will be much better if the app would have supported Material You theme.

That way we can just toggle 'Material You theme' option on instead of adding custom theme if we just want Monet Colours.

**Comment by AAGaming00** [comment]
I am working on this

**Comment by soymadip** [comment]
> I am working on this

Thanks a lot sir🙏 [for replying and feature]

**Comment by mangkoran** [comment]
~~Sorry to ask for this, but may I know if there is update regarding this FR?~~

Please ignore

**Comment by mangkoran** [comment]
Sorry again but it seems @nexpid has made a plugin that automatically load monet colors https://github.com/nexpid/VendettaMonetTheme. You might want to check it whether it is what you wanted.

**Comment by soymadip** [comment]
I guess I should close this now...

**Comment by nexpid** [comment]
https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/monet-theme

**Comment by soymadip** [comment]
> https://vd-plugins.github.io/proxy/vendetta.nexpid.xyz/monet-theme

Yeah I know😅 
That's why I closed it....
