### ISSUE TITLE
Why didn't anyone tell me about this mod? 😡 what is the intention of hiding this shit from me?

### ISSUE THREAD

**Issue by aicynide** [vendetta-mod/Vendetta#76]

**Comment by meqativ** [comment]
you were just not at the right time & place

**Comment by imrobbybobby** [comment]
![Screenshot_20230123_020604](https://user-images.githubusercontent.com/101864584/235375196-bd20e20d-6144-400b-a419-8a9151629d4a.png)

**Comment by aicynide** [comment]
Maybe i hadn't checked dickcord encyclopedia

**Comment by esibun** [comment]
![bear-home](https://user-images.githubusercontent.com/2644839/235567589-c69a879e-90df-448d-b254-ee28e700b445.gif)

**Comment by lexyclear** [comment]
this is actually real funny ngl but please don't waste the time of devs with nonessential dialogue . thank you 
also its spelled discord

**Comment by mantikafasi** [comment]
forgor

**Comment by jakeayy** [comment]
> you were just not at the right time & place

that guy still isn't at the right time and place

**Comment by VodkaXMartini** [comment]
skill issue

**Comment by meqativ** [comment]
not planned to tell them about this mod
