### ISSUE TITLE
how do i install

### ISSUE THREAD

**Issue by 3flowin** [vendetta-mod/Vendetta#8]
howowowow

**Comment by maisymoe** [comment]
Which platform are you on?
Do you have a jailbreak/are you rooted?

**Comment by 3flowin** [comment]
Im on android
not rooted

**Comment by maisymoe** [comment]
You should use [frendetta](https://github.com/vendetta-mod/frendetta). It's a script you'll need to run on a Linux computer. @redstonekasi is working on an Android app to remove the computer requirement, but it's not ready yet.

**Comment by 3flowin** [comment]
i dont have a linux pc ;(

**Comment by redstonekasi** [comment]
Sorry, the patcher app isn't done yet, if you don't have any way of patching the APK yourself, [here](https://files.k6.tf/discord/163205) is a prepatched version, install it using Split APKs Installer (SAI).
