### ISSUE TITLE
error message saying "cannot install, unknown reason"

### ISSUE THREAD

**Issue by cuilean** [vendetta-mod/Vendetta#84]
when i try to download from the manager, everything seems to work until i press install for vendetta and it tells me it can't install. i tried using the base apks in both stable folders and while it does install it doesn't open. i tried on my other phone (xiaomi) and it's the same thing.

**Comment by XAlboX** [comment]
Solution -> turn off MIUI optimization

P.S. To install an apks you can't just install base.apk For the future

**Comment by cuilean** [comment]
> Solution -> turn off MIUI optimization
> 
> P.S. To install an apks you can't just install base.apk For the future

my main phone is oneplus and it has the same error for the manager. as for the alternative method i realize that using the base by itself wasn't going to work but i used sai for the split+base and it still didn't work. unless i'm doing that wrong as well?

**Comment by XAlboX** [comment]
Base + config arm64/armeabi + config xxhdpi + config en

**Comment by cuilean** [comment]
thank you, alternative method worked!
