### ISSUE TITLE
[Question] Where is Vendetta's plugin folder ?

### ISSUE THREAD

**Issue by KaKi87** [vendetta-mod/Vendetta#94]
Thanks

**Comment by NullCode1337** [comment]
plugins are loaded from URLs, find them in the vendetta discord server

**Comment by KaKi87** [comment]
Of course, but I want to be able to copy these, so I can export and import my entire plugin list in one click when setting up new devices.
Thanks

**Comment by 2u9** [comment]
you can possibly use plugin "Addon List" which sends all your plugins with urls to download them, but it might not be as efficient as the copying and pasting them all manually

**Comment by XAlboX** [comment]
At the moment there is a plugin (non-proxied) called screwdriver that allows you to make a backup.
It's incomplete because Beef wants to implement something like Vencord Cloud but for Vendetta.

**Comment by KaKi87** [comment]
So there can't be a simple solution like archiving a directory as I do with Aliucord and BetterDiscord ?

Regarding URLs, would it be possible to paste them all at once ?

**Comment by XAlboX** [comment]
I told you. You can use screwdriver to save all your plugins and their settings and then import them into the new app.

**Comment by XAlboX** [comment]
I just remembered now that the backup plugin is MigrationStation.
Screwdriver is for another reason.
Skill issue time
