### ISSUE TITLE
Marked as Trojan

### ISSUE THREAD

**Issue by RaptaG** [vendetta-mod/Vendetta#96]
This happened after Vendetta and Discord update:

![Screenshot_2023-06-15-21-06-04-533_com.miui.global.packageinstaller.jpg](https://github.com/vendetta-mod/Vendetta/assets/77157639/460d0f26-c020-4be8-b61a-2fd0b53f64f6)

**Comment by RaptaG** [comment]
Yes I have manually renamed and changed the Vendetta icon from the Manager's Settings

**Comment by wingio** [comment]
Someone uploaded Vendetta to some av database or smth, you can ignore it

**Comment by RaptaG** [comment]
Alright! I suggest you pin this so people can refer to this when they stumble across something like that.

**Comment by Darksound9** [comment]
Also detected on MIUI Global 14.0.7 TKHEUXM.

**Comment by win98se** [comment]
PRC phone companies like to mark third-party apps as malicious; Those so-called `warnings` can be safely ignored.

**Comment by maisymoe** [comment]
Evo-gen is some generic Android virus (hence "gen").
LSPatch, our injection method (LSPosed/Xposed Framework but embedded into the app) was probably put on some virus database marked as Evo-gen.

This is likely the case for several reasons, but most notably that people with TwiFucker injected into their Twitter app using LSPatch have seen it flagged malicious as well.
